repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Removes trailing whitespace from files.
      - id: end-of-file-fixer
        name: Ensure newline at end of file
        description: Ensures that files end with a newline.
      - id: check-yaml
        name: Check YAML files
        description: Validates YAML files for syntax errors.
      - id: debug-statements
        name: Detect debug statements
        description: Detects `print` and `pdb` statements in code.
      - id: name-tests-test
        name: Test name convention
        description: Ensures that test files start with `test_`.
      - id: requirements-txt-fixer
        name: Fix requirements.txt format
        description: Sorts and cleans up requirements.txt.

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        name: Upgrade syntax for newer versions of Python
        description: Automatically upgrades syntax for newer versions of Python.
        args: [--py39-plus]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports
        description: Reorders Python imports based on PEP8 guidelines.
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus]

  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
      - id: unimport
        name: Remove unused imports
        description: Detects and removes unused imports in Python files.

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        name: Add trailing commas
        description: Adds trailing commas to multiline collections and function signatures.

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Flake8 code quality checker
        description: Checks code quality and style with flake8.
        args: [--max-line-length=99]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black code formatter
        description: Formats code with Black, the uncompromising code formatter.
        args: [--line-length=99]
